### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by DmitrySerg** [marcopeix/times-series-analysis#1]
Hi! I see you really enjoyed the Open Machine Learning course by OpenDataScience (mlcourse.ai), so you decided to write your own articles about time series analysis on Medium. That's great! We distribute all the content under Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0) license, which pretty much allows you to do whatever you want, given that you provide all the necessary links and credentials to the original content creators (you can check the full license text [here](https://github.com/Yorko/mlcourse.ai/blob/master/LICENSE.md)). 

Here's the link to the original article that you should cite - https://medium.com/open-machine-learning-course/open-machine-learning-course-topic-9-time-series-analysis-in-python-a270cb05e0b3

Please, add proper credentials to both articles you've posted:

- https://towardsdatascience.com/almost-everything-you-need-to-know-about-time-series-860241bdc578
- https://towardsdatascience.com/end-to-end-time-series-analysis-and-modelling-8c34f09a3014

**Comment by marcopeix** [comment]
Done!

On Feb 13, 2019 12:41 PM, Dmitry Sergeyev <notifications@github.com> wrote:

Hi! I see you really enjoyed the Open Machine Learning course by OpenDataScience (mlcourse.ai), so you decided to write your own articles about time series analysis on Medium. That's great! We distribute all the content under Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0) license, which pretty much allows you to do whatever you want, given that you provide all the necessary links and credentials to the original content creators (you can check the full license text here<https://github.com/Yorko/mlcourse.ai/blob/master/LICENSE.md>).

Here's the link to the original article that you should cite - https://medium.com/open-machine-learning-course/open-machine-learning-course-topic-9-time-series-analysis-in-python-a270cb05e0b3

Please, add proper credentials to both articles you've posted:

  *   https://towardsdatascience.com/almost-everything-you-need-to-know-about-time-series-860241bdc578
  *   https://towardsdatascience.com/end-to-end-time-series-analysis-and-modelling-8c34f09a3014

**Comment by DmitrySerg** [comment]
Thanks!
